name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/munchmobile:latest .

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/munchmobile:latest

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/munchmobile:latest
            docker stop munchmobile || true
            docker rm munchmobile || true
            docker run -d --name munchmobile -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/munchmobile:latest
          EOF
        env:
          DOCKER_USERNAME: ${{ secrets.sanyashirodkar }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
